### ISSUE TITLE
Laravel Echo private channel

### ISSUE THREAD

**Issue by ThunderPaul** [alefesouza/laravel-vue-boilerplate#1]
Hi,
I'm using Pusher as live notification system in your boilerplate, with public channel working fine, but I can't use private channel.

This is my code:

TheHeader.vue
```
(<any>window).Echo.private('App.User.' + this.userId)
    .listen('.job', (e) => {
        console.log(e.message);
    });
```

Event.php
```
public function broadcastOn()
    {
        return new PrivateChannel('App.User.'.$this->user->id);
    }
```

channel.php
```
Broadcast::channel('App.User.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});
```
When frontend call URL http://pusher.localhost/broadcasting/auth I have this error:

> Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
> No message

![image](https://user-images.githubusercontent.com/5073248/39312709-810706e6-4970-11e8-8dbb-3f81c1ba2be1.png)

Can you help me?

Thank you

**Comment by alefesouza** [comment]
Hello, I was able to reproduce this error, to fix it I just needed to uncomment "App\Providers\BroadcastServiceProvider::class" on the config/app.php file, I will also push a version with Pusher and Laravel Echo already configured, thanks for the idea!

**Comment by boyet007** [comment]
is this fix already?
