### ISSUE TITLE
Vue i18n not working

### ISSUE THREAD

**Issue by Yomanz** [alefesouza/laravel-vue-boilerplate#10]
Getting `[ts] Cannot find module '@/vue-i18n-locales.generated'`from: `resources/assets/vue/utils/i18n.ts` on line 6
`import Locales from '@/vue-i18n-locales.generated';`

Any ideas??

**Comment by alefesouza** [comment]
Run

`php artisan vue-i18n:generate`

to generate Vue i18n from Laravel translation files.
