### ISSUE TITLE
Error when run # php artisan migrate --seed

### ISSUE THREAD

**Issue by ElectroArmy** [alefesouza/laravel-vue-boilerplate#11]
$ php artisan migrate --seed
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

In Connection.php line 664:

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' (SQL: select * from inf
  ormation_schema.tables where table_schema = forge and table_name = migrations)

In Connector.php line 67:

  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'

**Comment by alefesouza** [comment]
Apparently your database connection settings on your .env is not correctly configured.
