### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by furqee** [alefesouza/laravel-vue-boilerplate#13]
![image](https://user-images.githubusercontent.com/48431440/71674765-f1ea4900-2d9d-11ea-8ac4-61185262e9c7.png)

**Comment by furqee** [comment]
My PHP configuration.
PHP 7.2.20 (cli) (built: Jul  2 2019 13:01:33) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans

**Comment by scriptburn** [comment]
You must install php-intl extension

`sudo apt install php-intl`

**Comment by furqee** [comment]
I have found the solution in php 7.2 you have to enable intl extension 
;extension=intl remove colon extension=intl
