### ISSUE TITLE
User Password added is PlainText

### ISSUE THREAD

**Issue by loreberti89** [alefesouza/laravel-vue-boilerplate#18]
Hello, I don't know if it is a Bug or I'am missing something in configuration but, I noticed that When I add new user from Administrator panel, the user password in User table on DB is saved on plaintext.

I have added 
```
public function setPasswordAttribute($value)
        {
            if($value != ""){
                $this->attributes['password'] = bcrypt($value);
            }
        }
```
on User Model, but I guess I missed something.
I Doubt that there is a bug so much big.

**Comment by alefesouza** [comment]
Thanks.
