### ISSUE TITLE
Can't login:  POST http://localhost:8080/api/login 500 (Internal Server Error)

### ISSUE THREAD

**Issue by mshahinaz29** [alefesouza/laravel-vue-boilerplate#20]
![Screenshot_653](https://user-images.githubusercontent.com/78835936/120605993-473df480-c481-11eb-9858-31636f33b813.jpg)
![Screenshot_652](https://user-images.githubusercontent.com/78835936/120605997-486f2180-c481-11eb-914f-9ba4feb39ad0.jpg)

**Comment by kefivitch** [comment]
If adding your `routes` inside the `web middleware` doesn't work for any reason then try adding this to `$middleware` into `Kernel.php`
```
protected $middleware = [
        //...
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
];
```

**Comment by mshahinaz29** [comment]
> If adding your `routes` inside the `web middleware` doesn't work for any reason then try adding this to `$middleware` into `Kernel.php`
> 
> ```
> protected $middleware = [
>         //...
>         \Illuminate\Session\Middleware\StartSession::class,
>         \Illuminate\View\Middleware\ShareErrorsFromSession::class,
> ];
> ```

Thanks! It worked.
